#
# application.yml — главный конфигурационный файл Spring Boot.

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.


card:
  crypto:
    key: ${CARD_CRYPTO_KEY}
    transformation: AES/ECB/PKCS5Padding
    validity: ${CARD_VALIDITY_PERIOD:36}


